server:
  port: 9100

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
authserver:
  hostname: http://localhost:9000
      
security:      
  oauth2:
    client:
      clientId: clientId
      clientSecret: secret
      accessTokenUri: ${authserver.hostname}/oauth/access_token
    resource:
      userInfoUri: ${authserver.hostname}/me
      tokenInfoUri: ${authserver.hostname}/oauth/check_token